In [2]:
import builder
builder.build()

Best solve ratios:
3426 Sliding Window Xor                                 98.92%
3222 Sliding Window Distinct Values                     98.81%
1650 Range Xor Queries                                  98.63%
3157 Collecting Numbers Distribution                    98.48%
3404 Permutation Subsequence                            98.36%
3427 Line Segments Trace I                              98.32%
3397 Permutation Order                                  98.25%
3217 Knight Moves Grid                                  98.24%
1624 Chessboard and Queens                              98.15%
3141 And Subset Count                                   97.98%

Worst solve ratios:
3401 Stick Difference                                   15.38%
1728 Inversion Probability                              18.36%
2418 Grid Path Construction                             26.67%
2402 Two Stacks Sorting                                 32.18%
1685 New Flight Routes                                  37.50%
1727 Candy Lottery                                      42.44%
2174 Removing Digits II                                 43.88%
3359 Minimal Grid Path                                  50.52%
3314 Mountain Range                                     50.94%
2081 Fixed-Length Paths II                              53.08%

Most solved problems:
1068 Weird Algorithm                                    140488 solves
1083 Missing Number                                     120922 solves
1069 Repetitions                                        105574 solves
1094 Increasing Array                                    99092 solves
1070 Permutations                                        87140 solves
1633 Dice Combinations                                   71314 solves
1621 Distinct Numbers                                    68364 solves
1634 Minimizing Coins                                    61612 solves
1071 Number Spiral                                       61590 solves
1617 Bit Strings                                         58610 solves

Least solved problems:
3401 Stick Difference                                       18 solves
3216 Bouncing Ball Cycle                                    44 solves
3109 K Subset Sums II                                       47 solves
3417 Border Subgrid Count I                                 49 solves
3402 Minimum Cost Pairs                                     49 solves
3358 Split into Two Paths                                   53 solves
3400 Raab Game II                                           53 solves
3232 Tournament Graph Distribution                          57 solves
3424 Distinct Sums Grid                                     58 solves
3418 Border Subgrid Count II                                58 solves

In [5]:
import pandas as pd

problems = pd.read_csv("data/cses_problems.csv")
problems.head(10)

     id             title  solves  attempts  solve_ratio
0  1068   Weird Algorithm  140495    147155     0.954742
1  1083    Missing Number  120930    126923     0.952782
2  1069       Repetitions  105583    109979     0.960029
3  1094  Increasing Array   99097    102789     0.964082
4  1070      Permutations   87147     89882     0.969571
5  1071     Number Spiral   61593     67172     0.916945
6  1072       Two Knights   46979     48502     0.968599
7  1092          Two Sets   51068     55077     0.927211
8  1617       Bit Strings   58611     61893     0.946973
9  1618    Trailing Zeros   54678     58218     0.939194

In [6]:
# Most solved problems
sorted_df = problems.sort_values(by="solves", ascending=False)
sorted_df.head(10)

      id              title  solves  attempts  solve_ratio
0   1068    Weird Algorithm  140495    147155     0.954742
1   1083     Missing Number  120930    126923     0.952782
2   1069        Repetitions  105583    109979     0.960029
3   1094   Increasing Array   99097    102789     0.964082
4   1070       Permutations   87147     89882     0.969571
59  1633  Dice Combinations   71315     75557     0.943857
24  1621   Distinct Numbers   68365     74070     0.922978
60  1634   Minimizing Coins   61613     66292     0.929418
5   1071      Number Spiral   61593     67172     0.916945
8   1617        Bit Strings   58611     61893     0.946973

In [7]:
# Least solved problems
sorted_df = problems.sort_values(by="solves", ascending=True)
sorted_df.head(10)

       id                          title  solves  attempts  solve_ratio
397  3401               Stick Difference      18       118     0.152542
371  3216            Bouncing Ball Cycle      44        62     0.709677
374  3109               K Subset Sums II      47        60     0.783333
326  3417         Border Subgrid Count I      49        89     0.550562
392  3402             Minimum Cost Pairs      49        66     0.742424
317  3358           Split into Two Paths      53        89     0.595506
328  3400                   Raab Game II      53        63     0.841270
337  3232  Tournament Graph Distribution      57        59     0.966102
385  3159        Replace with Difference      58        72     0.805556
291  3424             Distinct Sums Grid      58        96     0.604167

In [9]:
# Problems with highest solve ratio
sorted_df = problems.sort_values(by="solve_ratio", ascending=False)
sorted_df.head(10)

       id                            title  solves  attempts  solve_ratio
260  3426               Sliding Window Xor    1827      1847     0.989172
262  3222   Sliding Window Distinct Values    1497      1515     0.988119
122  1650                Range Xor Queries   23189     23511     0.986304
338  3157  Collecting Numbers Distribution      65        66     0.984848
362  3404          Permutation Subsequence     120       122     0.983607
227  3427            Line Segments Trace I     176       179     0.983240
173  3397                Permutation Order     451       459     0.982571
19   3217                Knight Moves Grid    2352      2394     0.982456
16   1624            Chessboard and Queens   22820     23249     0.981548
285  3141                 And Subset Count     194       198     0.979798

In [10]:
# Problems with lowest solve ratio
sorted_df = problems.sort_values(by="solve_ratio", ascending=True)
sorted_df.head(10)

       id                   title  solves  attempts  solve_ratio
397  3401        Stick Difference      18       118     0.152542
189  1728   Inversion Probability     383      2086     0.183605
293  2418  Grid Path Construction     108       405     0.266667
399  2402      Two Stacks Sorting     149       463     0.321814
321  1685       New Flight Routes     279       744     0.375000
188  1727           Candy Lottery    1151      2712     0.424410
383  2174      Removing Digits II     190       433     0.438799
71   3359       Minimal Grid Path    2030      4015     0.505604
75   3314          Mountain Range    1412      2771     0.509563
158  2081   Fixed-Length Paths II    1360      2562     0.530835